# Generated by Django 4.2.7 on 2024-01-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transactions_type',
            field=models.IntegerField(choices=[(1, 'Borrow'), (2, 'Return')], null=True),
        ),
        migrations.DeleteModel(
            name='Borrow_book',
        ),
    ]
