# Generated by Django 4.2.7 on 2024-01-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Books', '0002_books_is_borrowed_alter_review_user'),
        ('transactions', '0002_transactions_transactions_type_delete_borrow_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transactions_type',
        ),
        migrations.CreateModel(
            name='Borrow_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transactions_type', models.IntegerField(choices=[(1, 'Borrow'), (2, 'Return')], null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.books')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
