# Generated by Django 4.2.7 on 2024-01-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactions_transactions_type_borrow_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='transaction',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions'),
        ),
    ]
