# Generated by Django 4.2.7 on 2024-01-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_borrow_book_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='transaction',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions'),
        ),
    ]
